/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sets the `csrftoken` cookie; call once before the first unsafe request. */
        get: operations["auth_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["profile_get_goals"];
        put: operations["profile_update_goals"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Queue an AI search; poll `GET /api/queries/{id}` until status is done or error.
         *     The error text is logged server-side, not returned: it can contain provider details.
         */
        post: operations["queries_submit_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queries/{query_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["queries_query_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Search without AI: synchronous, at most KEYWORD_SEARCH_RESULT_COUNT recipes.
         *     `elapsed_ms` is database search time, measured here.
         */
        get: operations["recipes_keyword_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CredentialsRequest: {
            username: string;
            password: string;
        };
        /** @description PUT replaces every goal: a field left out is cleared (default None). */
        Goals: {
            /** Format: double */
            daily_calorie_target?: number | null;
            /** Format: double */
            protein_target_g?: number | null;
            /** Format: double */
            carbs_target_g?: number | null;
            /** Format: double */
            fat_target_g?: number | null;
            /** Format: double */
            fiber_target_g?: number | null;
        };
        /** @description PUT replaces every goal: a field left out is cleared (default None). */
        GoalsRequest: {
            /** Format: double */
            daily_calorie_target?: number | null;
            /** Format: double */
            protein_target_g?: number | null;
            /** Format: double */
            carbs_target_g?: number | null;
            /** Format: double */
            fat_target_g?: number | null;
            /** Format: double */
            fiber_target_g?: number | null;
        };
        Me: {
            username: string;
            is_staff: boolean;
        };
        Message: {
            detail: string;
        };
        QueryInRequest: {
            prompt: string;
        };
        QueryOut: {
            id: number;
            status: components["schemas"]["QueryStatus"];
            results: components["schemas"]["ResultOut"][] | null;
            /** Format: double */
            elapsed_seconds: number | null;
        };
        /**
         * @description * `pending` - Pending
         *     * `running` - Running
         *     * `done` - Done
         *     * `error` - Error
         * @enum {string}
         */
        QueryStatus: "pending" | "running" | "done" | "error";
        RecipeOut: {
            readonly id: number;
            readonly recipe_name: string;
            /** Format: uri */
            readonly source_url: string;
            /** Format: uri */
            readonly image_url: string | null;
            /** Format: double */
            readonly calories_per_serving: number | null;
            /** Format: double */
            readonly protein_g_per_serving: number | null;
            /** Format: double */
            readonly carbs_g_per_serving: number | null;
            /** Format: double */
            readonly fat_g_per_serving: number | null;
            /** Format: double */
            readonly fiber_g_per_serving: number | null;
            /** Format: double */
            readonly sugar_g_per_serving: number | null;
            /** Format: double */
            readonly sodium_mg_per_serving: number | null;
        };
        /** @description One entry of `QueryRequest.results` (see `queries.tasks._serialize_result`). */
        ResultOut: {
            recipe_id: number;
            recipe_name: string;
            description: string;
            source_url: string;
            image_url: string | null;
            /** Format: double */
            calories_per_serving: number | null;
            /** Format: double */
            protein_g_per_serving: number | null;
            /** Format: double */
            carbs_g_per_serving: number | null;
            /** Format: double */
            fat_g_per_serving: number | null;
            /** Format: double */
            fiber_g_per_serving: number | null;
            /** Format: double */
            sugar_g_per_serving: number | null;
            /** Format: double */
            sodium_mg_per_serving: number | null;
        };
        SearchOut: {
            query: string;
            results: components["schemas"]["RecipeOut"][];
            /** Format: double */
            elapsed_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    auth_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    profile_get_goals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goals"];
                };
            };
        };
    };
    profile_update_goals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GoalsRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goals"];
                };
            };
        };
    };
    queries_submit_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryInRequest"];
            };
        };
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryOut"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    queries_query_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryOut"];
                };
            };
        };
    };
    recipes_keyword_search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description No response body */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
