/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Csrf
         * @description Sets the `csrftoken` cookie; call once before the first unsafe request.
         */
        get: operations["accounts_api_csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login View */
        post: operations["accounts_api_login_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout View */
        post: operations["accounts_api_logout_view"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["accounts_api_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Goals */
        get: operations["accounts_api_get_goals"];
        /** Update Goals */
        put: operations["accounts_api_update_goals"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Query
         * @description Queue an AI search; poll `GET /api/queries/{id}` until status is done or error.
         *     The error text is logged server-side, not returned: it can contain provider details.
         */
        post: operations["queries_api_submit_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/queries/{query_request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query Status */
        get: operations["queries_api_query_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Keyword Search
         * @description Search without AI: synchronous, at most KEYWORD_SEARCH_RESULT_COUNT recipes.
         *     `elapsed_ms` is database search time, measured here.
         */
        get: operations["recipes_api_keyword_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Me */
        Me: {
            /** Username */
            username: string;
            /** Is Staff */
            is_staff: boolean;
        };
        /** Message */
        Message: {
            /** Detail */
            detail: string;
        };
        /** Credentials */
        Credentials: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Goals */
        Goals: {
            /** Daily Calorie Target */
            daily_calorie_target?: number | null;
            /** Protein Target G */
            protein_target_g?: number | null;
            /** Carbs Target G */
            carbs_target_g?: number | null;
            /** Fat Target G */
            fat_target_g?: number | null;
            /** Fiber Target G */
            fiber_target_g?: number | null;
        };
        /** QueryOut */
        QueryOut: {
            /** Id */
            id: number;
            status: components["schemas"]["Status"];
            /** Results */
            results: components["schemas"]["ResultOut"][] | null;
            /** Elapsed Seconds */
            elapsed_seconds: number | null;
        };
        /**
         * ResultOut
         * @description One entry of `QueryRequest.results` (see `queries.tasks._serialize_result`).
         */
        ResultOut: {
            /** Recipe Id */
            recipe_id: number;
            /** Recipe Name */
            recipe_name: string;
            /** Description */
            description: string;
            /** Source Url */
            source_url: string;
            /** Image Url */
            image_url: string | null;
            /** Calories Per Serving */
            calories_per_serving: number | null;
            /** Protein G Per Serving */
            protein_g_per_serving: number | null;
            /** Carbs G Per Serving */
            carbs_g_per_serving: number | null;
            /** Fat G Per Serving */
            fat_g_per_serving: number | null;
            /** Fiber G Per Serving */
            fiber_g_per_serving: number | null;
            /** Sugar G Per Serving */
            sugar_g_per_serving: number | null;
            /** Sodium Mg Per Serving */
            sodium_mg_per_serving: number | null;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "pending" | "running" | "done" | "error";
        /** QueryIn */
        QueryIn: {
            /** Prompt */
            prompt: string;
        };
        /** SearchParams */
        SearchParams: {
            /** Q */
            q: string;
        };
        /** RecipeOut */
        RecipeOut: {
            /** Id */
            id: number;
            /** Recipe Name */
            recipe_name: string;
            /** Source Url */
            source_url: string;
            /** Image Url */
            image_url: string | null;
            /** Calories Per Serving */
            calories_per_serving: number | null;
            /** Protein G Per Serving */
            protein_g_per_serving: number | null;
            /** Carbs G Per Serving */
            carbs_g_per_serving: number | null;
            /** Fat G Per Serving */
            fat_g_per_serving: number | null;
            /** Fiber G Per Serving */
            fiber_g_per_serving: number | null;
            /** Sugar G Per Serving */
            sugar_g_per_serving: number | null;
            /** Sodium Mg Per Serving */
            sodium_mg_per_serving: number | null;
        };
        /** SearchOut */
        SearchOut: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["RecipeOut"][];
            /** Elapsed Ms */
            elapsed_ms: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_api_csrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_login_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
        };
    };
    accounts_api_logout_view: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    accounts_api_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    accounts_api_get_goals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goals"];
                };
            };
        };
    };
    accounts_api_update_goals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Goals"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goals"];
                };
            };
        };
    };
    queries_api_submit_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QueryIn"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryOut"];
                };
            };
        };
    };
    queries_api_query_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                query_request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryOut"];
                };
            };
        };
    };
    recipes_api_keyword_search: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
        };
    };
}
