# Generated by Django 5.1.15 on 2026-10-09 03:29

import queries.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        # Added without a default first: with the callable default, AddField would stamp every
        # existing row with one "now + deadline" instead of leaving them for 0003 to backfill.
        migrations.AddField(
            model_name='queryrequest',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='expires_at',
            field=models.DateTimeField(default=queries.models._default_expiry, null=True),
        ),
        migrations.AddField(
            model_name='queryrequest',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
