# Generated by Django 5.1.15 on 2026-08-21 17:11

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('servings', models.FloatField()),
                ('ingredient_lines', models.JSONField(default=list)),
                ('diet_labels', models.JSONField(default=list)),
                ('health_labels', models.JSONField(default=list)),
                ('cautions', models.JSONField(default=list)),
                ('cuisine_type', models.JSONField(default=list)),
                ('meal_type', models.JSONField(default=list)),
                ('dish_type', models.JSONField(default=list)),
                ('calories_per_serving', models.FloatField(blank=True, null=True)),
                ('protein_g_per_serving', models.FloatField(blank=True, null=True)),
                ('carbs_g_per_serving', models.FloatField(blank=True, null=True)),
                ('fat_g_per_serving', models.FloatField(blank=True, null=True)),
                ('fiber_g_per_serving', models.FloatField(blank=True, null=True)),
                ('sugar_g_per_serving', models.FloatField(blank=True, null=True)),
                ('sodium_mg_per_serving', models.FloatField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipe_name', 'source_url'), name='unique_recipe_name_source_url')],
            },
        ),
    ]
