# Generated by Django 5.1.15 on 2026-08-21 20:41

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=384),
        ),
    ]
