# Generated by Django 5.1.15 on 2026-10-07 15:12

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_repo', models.CharField(max_length=200)),
                ('source_revision', models.CharField(max_length=64)),
                ('source_file', models.CharField(max_length=300)),
                ('file_sha256', models.CharField(max_length=64)),
                ('source_rows', models.PositiveIntegerField()),
                ('staged_rows', models.PositiveIntegerField(default=0)),
                ('rejected_rows', models.PositiveIntegerField(default=0)),
                ('inserted_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='embedded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='embedding_input_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='recipe',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_seen_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipes.ingestionrun'),
        ),
        # Bulk-load tables used by recipes.services.corpus_load. Raw SQL rather
        # than models: they're write-once scratch space for COPY, never read
        # through the ORM. UNLOGGED skips WAL; Postgres empties it after a crash,
        # which is fine because every load re-stages from the source file.
        migrations.RunSQL(
            sql="""
                CREATE UNLOGGED TABLE recipe_staging (
                    run_id                bigint NOT NULL,
                    row_number            integer NOT NULL,
                    recipe_name           varchar(500) NOT NULL,
                    source_url            varchar(1000) NOT NULL,
                    image_url             varchar(1000),
                    servings              double precision NOT NULL,
                    calories_per_serving  double precision,
                    protein_g_per_serving double precision,
                    fat_g_per_serving     double precision,
                    carbs_g_per_serving   double precision,
                    fiber_g_per_serving   double precision,
                    sugar_g_per_serving   double precision,
                    sodium_mg_per_serving double precision,
                    ingredient_lines      jsonb NOT NULL,
                    diet_labels           jsonb NOT NULL,
                    health_labels         jsonb NOT NULL,
                    cautions              jsonb NOT NULL,
                    cuisine_type          jsonb NOT NULL,
                    meal_type             jsonb NOT NULL,
                    dish_type             jsonb NOT NULL,
                    embedding_input_hash  varchar(64) NOT NULL
                );
                CREATE INDEX recipe_staging_run_id ON recipe_staging (run_id);
                CREATE TABLE ingestion_reject (
                    id         bigserial PRIMARY KEY,
                    run_id     bigint NOT NULL REFERENCES recipes_ingestionrun (id) ON DELETE CASCADE,
                    row_number integer NOT NULL,
                    reason     text NOT NULL,
                    raw        jsonb NOT NULL
                );
                CREATE INDEX ingestion_reject_run_id ON ingestion_reject (run_id);
            """,
            reverse_sql="DROP TABLE ingestion_reject; DROP TABLE recipe_staging;",
        ),
    ]
